-- Consolidated initial schema for Reverie.
-- Generated by pg_dump from the result of running migrations
-- 20260412150001 through 20260526015539, then cleaned and
-- augmented with grants and seed data.
--
-- Rollup PR: chore/migration-rollup

--------------------------------------------------------------------------------
-- 1. Extensions
--------------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

--------------------------------------------------------------------------------
-- 2. Enum types (final values only)
--------------------------------------------------------------------------------

CREATE TYPE public.api_cache_kind AS ENUM (
    'hit',
    'miss',
    'error'
);

CREATE TYPE public.author_role AS ENUM (
    'author',
    'editor',
    'translator',
    'narrator'
);

CREATE TYPE public.enrichment_status AS ENUM (
    'pending',
    'in_progress',
    'complete',
    'failed',
    'skipped'
);

CREATE TYPE public.ingestion_status AS ENUM (
    'pending',
    'processing',
    'complete',
    'failed',
    'skipped'
);

CREATE TYPE public.job_status AS ENUM (
    'queued',
    'running',
    'complete',
    'failed',
    'skipped'
);

CREATE TYPE public.manifestation_format AS ENUM (
    'epub',
    'pdf',
    'mobi',
    'azw3',
    'cbz',
    'cbr'
);

CREATE TYPE public.metadata_review_status AS ENUM (
    'pending',
    'rejected'
);

CREATE TYPE public.tag_type AS ENUM (
    'genre',
    'sub_genre',
    'trope',
    'theme'
);

CREATE TYPE public.theme_preference AS ENUM (
    'system',
    'light',
    'dark'
);

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'adult',
    'child'
);

CREATE TYPE public.validation_status AS ENUM (
    'pending',
    'valid',
    'repaired',
    'degraded'
);

CREATE TYPE public.writeback_status AS ENUM (
    'pending',
    'in_progress',
    'complete',
    'failed',
    'skipped'
);

--------------------------------------------------------------------------------
-- 3. Schemas
--------------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS tower_sessions;

--------------------------------------------------------------------------------
-- 4. Functions
--------------------------------------------------------------------------------

CREATE FUNCTION public.notify_settings_changed() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('settings_changed', '');
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.works_search_vector_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.search_vector := to_tsvector('english', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.description, ''));
    RETURN NEW;
END;
$$;

--------------------------------------------------------------------------------
-- 5. Tables (FK-dependency order)
--------------------------------------------------------------------------------

CREATE TABLE public.users (
    id uuid DEFAULT uuidv7() NOT NULL,
    oidc_subject text NOT NULL,
    display_name text NOT NULL,
    email text,
    role public.user_role DEFAULT 'adult'::public.user_role NOT NULL,
    is_child boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    session_version integer DEFAULT 0 NOT NULL,
    theme_preference public.theme_preference DEFAULT 'system'::public.theme_preference NOT NULL,
    CONSTRAINT chk_child_role_sync CHECK ((((is_child = true) AND (role = 'child'::public.user_role)) OR ((is_child = false) AND (role <> 'child'::public.user_role))))
);

CREATE TABLE public.works (
    id uuid DEFAULT uuidv7() NOT NULL,
    title text NOT NULL,
    sort_title text NOT NULL,
    description text,
    language text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    search_vector tsvector,
    title_version_id uuid,
    description_version_id uuid,
    language_version_id uuid
);

CREATE TABLE public.authors (
    id uuid DEFAULT uuidv7() NOT NULL,
    name text NOT NULL,
    sort_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.series (
    id uuid DEFAULT uuidv7() NOT NULL,
    name text NOT NULL,
    sort_name text NOT NULL,
    parent_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.metadata_sources (
    id text NOT NULL,
    display_name text NOT NULL,
    kind text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    base_priority integer NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.manifestations (
    id uuid DEFAULT uuidv7() NOT NULL,
    work_id uuid NOT NULL,
    isbn_10 text,
    isbn_13 text,
    publisher text,
    pub_date date,
    format public.manifestation_format NOT NULL,
    file_path text NOT NULL,
    ingestion_file_hash text CONSTRAINT manifestations_file_hash_not_null NOT NULL,
    file_size_bytes bigint NOT NULL,
    validation_status public.validation_status DEFAULT 'pending'::public.validation_status NOT NULL,
    ingestion_status public.ingestion_status DEFAULT 'pending'::public.ingestion_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    accessibility_metadata jsonb,
    publisher_version_id uuid,
    pub_date_version_id uuid,
    isbn_10_version_id uuid,
    isbn_13_version_id uuid,
    cover_path text,
    cover_sha256 bytea,
    cover_size_bytes bigint,
    cover_source text,
    cover_version_id uuid,
    suspected_duplicate_work_id uuid,
    enrichment_status public.enrichment_status DEFAULT 'pending'::public.enrichment_status NOT NULL,
    enrichment_attempted_at timestamp with time zone,
    enrichment_attempt_count integer DEFAULT 0 NOT NULL,
    enrichment_error text,
    current_file_hash text NOT NULL
);

COMMENT ON TABLE public.manifestations IS 'RLS enabled. reverie_app handlers must SET LOCAL app.current_user_id in a transaction. The writeback worker connects via a dedicated pool that sets app.system_context = ''writeback'' (session-scoped via after_connect). reverie_ingestion has unconditional access. reverie (owner) bypasses RLS.';
COMMENT ON COLUMN public.manifestations.ingestion_file_hash IS 'SHA-256 of file at ingestion time. Immutable after initial insert — audit trail.';
COMMENT ON COLUMN public.manifestations.current_file_hash IS 'SHA-256 of file as of last successful writeback. Equals ingestion_file_hash until first writeback. Step 11 health surfaces divergence from on-disk hash.';

CREATE TABLE public.metadata_versions (
    id uuid DEFAULT uuidv7() NOT NULL,
    manifestation_id uuid NOT NULL,
    source text NOT NULL,
    field_name text NOT NULL,
    old_value jsonb,
    new_value jsonb NOT NULL,
    status public.metadata_review_status DEFAULT 'pending'::public.metadata_review_status NOT NULL,
    confidence_score real NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by uuid,
    value_hash bytea NOT NULL,
    match_type text NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    observation_count integer DEFAULT 1 NOT NULL
);

CREATE TABLE public.work_authors (
    work_id uuid NOT NULL,
    author_id uuid NOT NULL,
    role public.author_role DEFAULT 'author'::public.author_role NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    source_version_id uuid
);

CREATE TABLE public.series_works (
    series_id uuid NOT NULL,
    work_id uuid NOT NULL,
    "position" numeric,
    is_omnibus boolean DEFAULT false NOT NULL,
    note text
);

CREATE TABLE public.omnibus_contents (
    omnibus_manifestation_id uuid NOT NULL,
    contained_work_id uuid NOT NULL,
    "position" integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.tags (
    id uuid DEFAULT uuidv7() NOT NULL,
    name text NOT NULL,
    tag_type public.tag_type NOT NULL
);

CREATE TABLE public.manifestation_tags (
    manifestation_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    source_version_id uuid
);

CREATE TABLE public.field_locks (
    manifestation_id uuid NOT NULL,
    entity_type text NOT NULL,
    field_name text NOT NULL,
    locked_at timestamp with time zone DEFAULT now() NOT NULL,
    locked_by uuid
);

CREATE TABLE public.shelves (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.shelf_items (
    shelf_id uuid NOT NULL,
    manifestation_id uuid NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL,
    "position" integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.device_tokens (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    token_hash text NOT NULL,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone
);

CREATE TABLE public.api_cache (
    id uuid DEFAULT uuidv7() NOT NULL,
    source text NOT NULL,
    lookup_key text NOT NULL,
    response jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    response_kind public.api_cache_kind DEFAULT 'hit'::public.api_cache_kind NOT NULL,
    http_status integer
);

CREATE TABLE public.ingestion_jobs (
    id uuid DEFAULT uuidv7() NOT NULL,
    batch_id uuid NOT NULL,
    source_path text NOT NULL,
    status public.job_status DEFAULT 'queued'::public.job_status NOT NULL,
    error_message text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.webhooks (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    url text NOT NULL,
    events jsonb DEFAULT '[]'::jsonb NOT NULL,
    payload_template text,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.webhook_deliveries (
    id uuid DEFAULT uuidv7() NOT NULL,
    webhook_id uuid NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    response_status integer,
    delivered_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.reading_sessions (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    manifestation_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    duration_seconds integer
);

CREATE TABLE public.reading_state (
    user_id uuid NOT NULL,
    manifestation_id uuid NOT NULL,
    progress_pct real,
    last_read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT reading_state_progress_paired_with_timestamp CHECK (((progress_pct IS NULL) = (last_read_at IS NULL))),
    CONSTRAINT reading_state_progress_pct_range CHECK (((progress_pct IS NULL) OR ((progress_pct >= (0)::double precision) AND (progress_pct <= (100)::double precision))))
);

COMMENT ON TABLE public.reading_state IS 'RLS enabled. reverie_app and reverie_readonly must SET LOCAL app.current_user_id in a transaction. Each user sees only rows where user_id matches the GUC. reverie (owner) bypasses RLS.';

CREATE TABLE public.writeback_jobs (
    id uuid DEFAULT uuidv7() NOT NULL,
    manifestation_id uuid NOT NULL,
    reason text NOT NULL,
    status public.writeback_status DEFAULT 'pending'::public.writeback_status NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempted_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT writeback_jobs_reason_chk CHECK ((reason = ANY (ARRAY['metadata'::text, 'cover'::text])))
);

COMMENT ON TABLE public.writeback_jobs IS 'Queue of pending/in-flight OPF writeback operations. One row per canonical pointer move. Drained by services::writeback::queue.';
COMMENT ON COLUMN public.writeback_jobs.reason IS '''metadata'' for text/field pointer moves; ''cover'' when a new cover sidecar needs embedding.';
COMMENT ON COLUMN public.writeback_jobs.status IS 'pending → in_progress → (complete | failed | skipped). ''skipped'' is terminal; see enum comment.';

CREATE TABLE public.settings (
    id boolean DEFAULT true NOT NULL,
    enrichment_enabled boolean DEFAULT true NOT NULL,
    enrichment_concurrency integer DEFAULT 2 NOT NULL,
    enrichment_poll_idle_secs integer DEFAULT 30 NOT NULL,
    enrichment_fetch_budget_secs integer DEFAULT 15 NOT NULL,
    cover_max_bytes bigint DEFAULT 10485760 NOT NULL,
    cover_download_timeout_secs integer DEFAULT 30 NOT NULL,
    cover_min_long_edge_px integer DEFAULT 1000 NOT NULL,
    cover_redirect_limit integer DEFAULT 3 NOT NULL,
    writeback_enabled boolean DEFAULT true NOT NULL,
    writeback_concurrency integer DEFAULT 2 NOT NULL,
    writeback_poll_idle_secs integer DEFAULT 5 NOT NULL,
    writeback_max_attempts integer DEFAULT 3 NOT NULL,
    opds_enabled boolean DEFAULT true NOT NULL,
    opds_page_size integer DEFAULT 50 NOT NULL,
    format_priority text[] DEFAULT '{epub,pdf,mobi,azw3,cbz,cbr}'::text[] NOT NULL,
    cleanup_mode text DEFAULT 'all'::text NOT NULL,
    openlibrary_base_url text DEFAULT 'https://openlibrary.org'::text NOT NULL,
    googlebooks_base_url text DEFAULT 'https://www.googleapis.com/books/v1'::text NOT NULL,
    hardcover_base_url text DEFAULT 'https://api.hardcover.app/v1/graphql'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT settings_cleanup_mode_check CHECK ((cleanup_mode = ANY (ARRAY['all'::text, 'ingested'::text, 'none'::text]))),
    CONSTRAINT settings_enrichment_concurrency_check CHECK (((enrichment_concurrency >= 1) AND (enrichment_concurrency <= 10))),
    CONSTRAINT settings_opds_page_size_check CHECK (((opds_page_size >= 1) AND (opds_page_size <= 500))),
    CONSTRAINT settings_writeback_concurrency_check CHECK (((writeback_concurrency >= 1) AND (writeback_concurrency <= 10))),
    CONSTRAINT settings_enrichment_poll_idle_secs_check CHECK ((enrichment_poll_idle_secs >= 1)),
    CONSTRAINT settings_enrichment_fetch_budget_secs_check CHECK ((enrichment_fetch_budget_secs >= 1)),
    CONSTRAINT settings_cover_max_bytes_check CHECK ((cover_max_bytes >= 1)),
    CONSTRAINT settings_cover_download_timeout_secs_check CHECK ((cover_download_timeout_secs >= 1)),
    CONSTRAINT settings_cover_min_long_edge_px_check CHECK ((cover_min_long_edge_px >= 1)),
    CONSTRAINT settings_cover_redirect_limit_check CHECK ((cover_redirect_limit >= 0)),
    CONSTRAINT settings_writeback_poll_idle_secs_check CHECK ((writeback_poll_idle_secs >= 1)),
    CONSTRAINT settings_writeback_max_attempts_check CHECK ((writeback_max_attempts >= 1)),
    CONSTRAINT singleton CHECK ((id = true))
);

CREATE TABLE tower_sessions.session (
    id text NOT NULL,
    data bytea NOT NULL,
    expiry_date timestamp with time zone NOT NULL
);

--------------------------------------------------------------------------------
-- 6. Primary keys and unique constraints
--------------------------------------------------------------------------------

ALTER TABLE ONLY public.api_cache
    ADD CONSTRAINT api_cache_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_cache
    ADD CONSTRAINT api_cache_source_lookup_key_key UNIQUE (source, lookup_key);

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_name_unique UNIQUE (name);

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.field_locks
    ADD CONSTRAINT field_locks_pkey PRIMARY KEY (manifestation_id, entity_type, field_name);

ALTER TABLE ONLY public.ingestion_jobs
    ADD CONSTRAINT ingestion_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.manifestation_tags
    ADD CONSTRAINT manifestation_tags_pkey PRIMARY KEY (manifestation_id, tag_id);

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_file_hash_unique UNIQUE (ingestion_file_hash);

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_file_path_key UNIQUE (file_path);

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.metadata_sources
    ADD CONSTRAINT metadata_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.metadata_versions
    ADD CONSTRAINT metadata_versions_mfs_hash_unique UNIQUE (manifestation_id, source, field_name, value_hash);

ALTER TABLE ONLY public.metadata_versions
    ADD CONSTRAINT metadata_versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.omnibus_contents
    ADD CONSTRAINT omnibus_contents_pkey PRIMARY KEY (omnibus_manifestation_id, contained_work_id);

ALTER TABLE ONLY public.reading_sessions
    ADD CONSTRAINT reading_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reading_state
    ADD CONSTRAINT reading_state_pkey PRIMARY KEY (user_id, manifestation_id);

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_name_unique UNIQUE (name);

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.series_works
    ADD CONSTRAINT series_works_pkey PRIMARY KEY (series_id, work_id);

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shelf_items
    ADD CONSTRAINT shelf_items_pkey PRIMARY KEY (shelf_id, manifestation_id);

ALTER TABLE ONLY public.shelves
    ADD CONSTRAINT shelves_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_name_tag_type_key UNIQUE (name, tag_type);

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_oidc_subject_key UNIQUE (oidc_subject);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webhooks
    ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.work_authors
    ADD CONSTRAINT work_authors_pkey PRIMARY KEY (work_id, author_id, role);

ALTER TABLE ONLY public.works
    ADD CONSTRAINT works_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.writeback_jobs
    ADD CONSTRAINT writeback_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tower_sessions.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);

--------------------------------------------------------------------------------
-- 7. Indexes
--------------------------------------------------------------------------------

CREATE INDEX idx_api_cache_expires_at ON public.api_cache USING btree (expires_at);

CREATE INDEX idx_authors_name_trgm ON public.authors USING gist (name public.gist_trgm_ops);

CREATE INDEX idx_device_tokens_user_id ON public.device_tokens USING btree (user_id);

CREATE INDEX idx_ingestion_jobs_batch_id ON public.ingestion_jobs USING btree (batch_id);

CREATE INDEX idx_ingestion_jobs_status ON public.ingestion_jobs USING btree (status);

CREATE INDEX idx_manifestation_tags_tag_id ON public.manifestation_tags USING btree (tag_id);

CREATE INDEX idx_manifestations_enrichment_queue ON public.manifestations USING btree (enrichment_status, enrichment_attempted_at NULLS FIRST) WHERE (enrichment_status = ANY (ARRAY['pending'::public.enrichment_status, 'failed'::public.enrichment_status]));

CREATE INDEX idx_manifestations_isbn_13 ON public.manifestations USING btree (isbn_13) WHERE (isbn_13 IS NOT NULL);

CREATE INDEX idx_manifestations_work_id ON public.manifestations USING btree (work_id);

CREATE INDEX idx_metadata_versions_resolved_by ON public.metadata_versions USING btree (resolved_by) WHERE (resolved_by IS NOT NULL);

CREATE INDEX idx_mv_last_seen ON public.metadata_versions USING btree (last_seen_at);

CREATE INDEX idx_mv_manifestation_field ON public.metadata_versions USING btree (manifestation_id, field_name);

CREATE INDEX idx_omnibus_contents_contained_work_id ON public.omnibus_contents USING btree (contained_work_id);

CREATE INDEX idx_reading_sessions_manifestation_id ON public.reading_sessions USING btree (manifestation_id);

CREATE INDEX idx_reading_sessions_user_id ON public.reading_sessions USING btree (user_id);

CREATE INDEX idx_reading_state_manifestation_id ON public.reading_state USING btree (manifestation_id);

CREATE INDEX idx_reading_state_user_last_read ON public.reading_state USING btree (user_id, last_read_at DESC NULLS LAST);

CREATE INDEX idx_series_name_trgm ON public.series USING gist (name public.gist_trgm_ops);

CREATE INDEX idx_series_parent_id ON public.series USING btree (parent_id) WHERE (parent_id IS NOT NULL);

CREATE INDEX idx_series_works_work_id ON public.series_works USING btree (work_id);

CREATE INDEX idx_shelf_items_manifestation_id ON public.shelf_items USING btree (manifestation_id);

CREATE INDEX idx_shelves_user_id ON public.shelves USING btree (user_id);

CREATE UNIQUE INDEX idx_users_email_lower ON public.users USING btree (lower(email)) WHERE (email IS NOT NULL);

CREATE INDEX idx_webhook_deliveries_webhook_id ON public.webhook_deliveries USING btree (webhook_id);

CREATE INDEX idx_webhooks_user_id ON public.webhooks USING btree (user_id);

CREATE INDEX idx_work_authors_author_id ON public.work_authors USING btree (author_id);

CREATE INDEX idx_works_search_vector ON public.works USING gin (search_vector);

CREATE INDEX idx_works_sort_title_id ON public.works USING btree (sort_title, id);

CREATE INDEX idx_works_title_trgm ON public.works USING gist (title public.gist_trgm_ops);

CREATE UNIQUE INDEX idx_writeback_jobs_in_progress_unique ON public.writeback_jobs USING btree (manifestation_id) WHERE (status = 'in_progress'::public.writeback_status);

COMMENT ON INDEX public.idx_writeback_jobs_in_progress_unique IS 'Enforces at most one in_progress writeback job per manifestation. Load-bearing for multi-replica correctness; see services::writeback::queue::claim_next for the retry path on SQLSTATE 23505.';

CREATE INDEX idx_writeback_jobs_manifestation_status ON public.writeback_jobs USING btree (manifestation_id, status);

CREATE INDEX idx_writeback_jobs_queue ON public.writeback_jobs USING btree (last_attempted_at NULLS FIRST, created_at) WHERE (status = ANY (ARRAY['pending'::public.writeback_status, 'failed'::public.writeback_status]));

CREATE INDEX session_expiry_date_idx ON tower_sessions.session USING btree (expiry_date);

CREATE INDEX idx_manifestations_cover_source ON public.manifestations USING btree (cover_source) WHERE (cover_source IS NOT NULL);

CREATE INDEX idx_manifestations_suspected_duplicate_work_id ON public.manifestations USING btree (suspected_duplicate_work_id) WHERE (suspected_duplicate_work_id IS NOT NULL);

CREATE INDEX idx_manifestations_cover_version_id ON public.manifestations USING btree (cover_version_id) WHERE (cover_version_id IS NOT NULL);

CREATE INDEX idx_manifestations_isbn_10_version_id ON public.manifestations USING btree (isbn_10_version_id) WHERE (isbn_10_version_id IS NOT NULL);

CREATE INDEX idx_manifestations_isbn_13_version_id ON public.manifestations USING btree (isbn_13_version_id) WHERE (isbn_13_version_id IS NOT NULL);

CREATE INDEX idx_manifestations_pub_date_version_id ON public.manifestations USING btree (pub_date_version_id) WHERE (pub_date_version_id IS NOT NULL);

CREATE INDEX idx_manifestations_publisher_version_id ON public.manifestations USING btree (publisher_version_id) WHERE (publisher_version_id IS NOT NULL);

CREATE INDEX idx_manifestation_tags_source_version_id ON public.manifestation_tags USING btree (source_version_id) WHERE (source_version_id IS NOT NULL);

CREATE INDEX idx_work_authors_source_version_id ON public.work_authors USING btree (source_version_id) WHERE (source_version_id IS NOT NULL);

CREATE INDEX idx_works_title_version_id ON public.works USING btree (title_version_id) WHERE (title_version_id IS NOT NULL);

CREATE INDEX idx_works_description_version_id ON public.works USING btree (description_version_id) WHERE (description_version_id IS NOT NULL);

CREATE INDEX idx_works_language_version_id ON public.works USING btree (language_version_id) WHERE (language_version_id IS NOT NULL);

CREATE INDEX idx_metadata_versions_source ON public.metadata_versions USING btree (source);

CREATE INDEX idx_field_locks_locked_by ON public.field_locks USING btree (locked_by) WHERE (locked_by IS NOT NULL);

--------------------------------------------------------------------------------
-- 8. Triggers
--------------------------------------------------------------------------------

CREATE TRIGGER settings_changed_trigger AFTER UPDATE ON public.settings FOR EACH ROW EXECUTE FUNCTION public.notify_settings_changed();

CREATE TRIGGER shelves_set_updated_at BEFORE UPDATE ON public.shelves FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_manifestations_updated_at BEFORE UPDATE ON public.manifestations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_reading_state_updated_at BEFORE UPDATE ON public.reading_state FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_works_search_vector BEFORE INSERT OR UPDATE OF title, description ON public.works FOR EACH ROW EXECUTE FUNCTION public.works_search_vector_update();

CREATE TRIGGER trg_works_updated_at BEFORE UPDATE ON public.works FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--------------------------------------------------------------------------------
-- 9. Foreign keys
--------------------------------------------------------------------------------

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.field_locks
    ADD CONSTRAINT field_locks_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.field_locks
    ADD CONSTRAINT field_locks_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.manifestation_tags
    ADD CONSTRAINT manifestation_tags_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.manifestation_tags
    ADD CONSTRAINT manifestation_tags_source_version_id_fkey FOREIGN KEY (source_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestation_tags
    ADD CONSTRAINT manifestation_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_cover_source_fkey FOREIGN KEY (cover_source) REFERENCES public.metadata_sources(id);

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_cover_version_id_fkey FOREIGN KEY (cover_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_isbn_10_version_id_fkey FOREIGN KEY (isbn_10_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_isbn_13_version_id_fkey FOREIGN KEY (isbn_13_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_pub_date_version_id_fkey FOREIGN KEY (pub_date_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_publisher_version_id_fkey FOREIGN KEY (publisher_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_suspected_duplicate_work_id_fkey FOREIGN KEY (suspected_duplicate_work_id) REFERENCES public.works(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.manifestations
    ADD CONSTRAINT manifestations_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.metadata_versions
    ADD CONSTRAINT metadata_versions_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.metadata_versions
    ADD CONSTRAINT metadata_versions_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.metadata_versions
    ADD CONSTRAINT metadata_versions_source_fk FOREIGN KEY (source) REFERENCES public.metadata_sources(id);

ALTER TABLE ONLY public.omnibus_contents
    ADD CONSTRAINT omnibus_contents_contained_work_id_fkey FOREIGN KEY (contained_work_id) REFERENCES public.works(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.omnibus_contents
    ADD CONSTRAINT omnibus_contents_omnibus_manifestation_id_fkey FOREIGN KEY (omnibus_manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reading_sessions
    ADD CONSTRAINT reading_sessions_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reading_sessions
    ADD CONSTRAINT reading_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reading_state
    ADD CONSTRAINT reading_state_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reading_state
    ADD CONSTRAINT reading_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.series(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.series_works
    ADD CONSTRAINT series_works_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.series_works
    ADD CONSTRAINT series_works_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.shelf_items
    ADD CONSTRAINT shelf_items_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.shelf_items
    ADD CONSTRAINT shelf_items_shelf_id_fkey FOREIGN KEY (shelf_id) REFERENCES public.shelves(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.shelves
    ADD CONSTRAINT shelves_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES public.webhooks(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.webhooks
    ADD CONSTRAINT webhooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.work_authors
    ADD CONSTRAINT work_authors_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.work_authors
    ADD CONSTRAINT work_authors_source_version_id_fkey FOREIGN KEY (source_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.work_authors
    ADD CONSTRAINT work_authors_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.works
    ADD CONSTRAINT works_description_version_id_fkey FOREIGN KEY (description_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.works
    ADD CONSTRAINT works_language_version_id_fkey FOREIGN KEY (language_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.works
    ADD CONSTRAINT works_title_version_id_fkey FOREIGN KEY (title_version_id) REFERENCES public.metadata_versions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.writeback_jobs
    ADD CONSTRAINT writeback_jobs_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestations(id) ON DELETE CASCADE;

--------------------------------------------------------------------------------
-- 10. Row-level security
--------------------------------------------------------------------------------

ALTER TABLE public.manifestations ENABLE ROW LEVEL SECURITY;

CREATE POLICY manifestations_delete ON public.manifestations FOR DELETE TO reverie_app USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid) AND (users.role = ANY (ARRAY['admin'::public.user_role, 'adult'::public.user_role]))))));

CREATE POLICY manifestations_ingestion_full_access ON public.manifestations TO reverie_ingestion USING (true) WITH CHECK (true);

CREATE POLICY manifestations_insert ON public.manifestations FOR INSERT TO reverie_app WITH CHECK ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid) AND (users.role = ANY (ARRAY['admin'::public.user_role, 'adult'::public.user_role]))))));

CREATE POLICY manifestations_select_adult ON public.manifestations FOR SELECT TO reverie_app, reverie_readonly USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid) AND (users.role = ANY (ARRAY['admin'::public.user_role, 'adult'::public.user_role]))))));

CREATE POLICY manifestations_select_child ON public.manifestations FOR SELECT TO reverie_app, reverie_readonly USING (((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid) AND (users.role = 'child'::public.user_role)))) AND (EXISTS ( SELECT 1
   FROM (public.shelf_items si
     JOIN public.shelves s ON ((s.id = si.shelf_id)))
  WHERE ((si.manifestation_id = manifestations.id) AND (s.user_id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid))))));

CREATE POLICY manifestations_select_system ON public.manifestations FOR SELECT TO reverie_app USING (((SELECT current_setting('app.system_context'::text, true)) = 'writeback'::text));

CREATE POLICY manifestations_update ON public.manifestations FOR UPDATE TO reverie_app USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid) AND (users.role = ANY (ARRAY['admin'::public.user_role, 'adult'::public.user_role])))))) WITH CHECK (true);

CREATE POLICY manifestations_update_system ON public.manifestations FOR UPDATE TO reverie_app USING (((SELECT current_setting('app.system_context'::text, true)) = 'writeback'::text)) WITH CHECK (true);

ALTER TABLE public.reading_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY reading_state_owner ON public.reading_state TO reverie_app, reverie_readonly USING ((user_id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid)) WITH CHECK ((user_id = ((SELECT current_setting('app.current_user_id'::text, true)))::uuid));

ALTER TABLE public.reading_sessions ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.reading_sessions IS 'RLS enabled (default deny). No handlers implemented yet. Define policies before implementing handlers.';

ALTER TABLE public.webhooks ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.webhooks IS 'RLS enabled (default deny). No handlers implemented yet. Define policies before implementing handlers.';

ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.webhook_deliveries IS 'RLS enabled (default deny). No handlers implemented yet. Access scoped through webhooks ownership. Define policies before implementing handlers.';

COMMENT ON TABLE public.shelves IS 'No RLS. Ownership enforced at application layer — all queries scope by user_id. See routes/shelves/ THREAT annotation.';

COMMENT ON TABLE public.device_tokens IS 'No RLS. Ownership enforced at application layer — all queries scope by user_id.';

--------------------------------------------------------------------------------
-- 11. Grants
--------------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO reverie_app;
GRANT USAGE ON SCHEMA public TO reverie_ingestion;
GRANT USAGE ON SCHEMA public TO reverie_readonly;
GRANT USAGE ON SCHEMA tower_sessions TO reverie_app;
GRANT USAGE ON SCHEMA tower_sessions TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.api_cache TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.api_cache TO reverie_ingestion;
GRANT SELECT ON TABLE public.api_cache TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.authors TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.authors TO reverie_ingestion;
GRANT SELECT ON TABLE public.authors TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.device_tokens TO reverie_app;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.field_locks TO reverie_app;
GRANT SELECT ON TABLE public.field_locks TO reverie_readonly;
GRANT SELECT ON TABLE public.field_locks TO reverie_ingestion;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ingestion_jobs TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ingestion_jobs TO reverie_ingestion;
GRANT SELECT ON TABLE public.ingestion_jobs TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.manifestation_tags TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.manifestation_tags TO reverie_ingestion;
GRANT SELECT ON TABLE public.manifestation_tags TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.manifestations TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.manifestations TO reverie_ingestion;
GRANT SELECT ON TABLE public.manifestations TO reverie_readonly;

GRANT SELECT ON TABLE public.metadata_sources TO reverie_app;
GRANT SELECT ON TABLE public.metadata_sources TO reverie_ingestion;
GRANT SELECT ON TABLE public.metadata_sources TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.metadata_versions TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.metadata_versions TO reverie_ingestion;
GRANT SELECT ON TABLE public.metadata_versions TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.omnibus_contents TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.omnibus_contents TO reverie_ingestion;
GRANT SELECT ON TABLE public.omnibus_contents TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.reading_sessions TO reverie_app;
GRANT SELECT ON TABLE public.reading_sessions TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.reading_state TO reverie_app;
GRANT SELECT ON TABLE public.reading_state TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.series TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.series TO reverie_ingestion;
GRANT SELECT ON TABLE public.series TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.series_works TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.series_works TO reverie_ingestion;
GRANT SELECT ON TABLE public.series_works TO reverie_readonly;

GRANT SELECT,UPDATE ON TABLE public.settings TO reverie_app;
GRANT SELECT ON TABLE public.settings TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shelf_items TO reverie_app;
GRANT SELECT ON TABLE public.shelf_items TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shelves TO reverie_app;
GRANT SELECT ON TABLE public.shelves TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tags TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tags TO reverie_ingestion;
GRANT SELECT ON TABLE public.tags TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.users TO reverie_app;
GRANT SELECT ON TABLE public.users TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.webhook_deliveries TO reverie_app;
GRANT SELECT ON TABLE public.webhook_deliveries TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.webhooks TO reverie_app;
GRANT SELECT ON TABLE public.webhooks TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.work_authors TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.work_authors TO reverie_ingestion;
GRANT SELECT ON TABLE public.work_authors TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.works TO reverie_app;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.works TO reverie_ingestion;
GRANT SELECT ON TABLE public.works TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.writeback_jobs TO reverie_app;
GRANT SELECT,INSERT ON TABLE public.writeback_jobs TO reverie_ingestion;
GRANT SELECT ON TABLE public.writeback_jobs TO reverie_readonly;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tower_sessions.session TO reverie_app;
GRANT SELECT(id) ON TABLE tower_sessions.session TO reverie_readonly;
GRANT SELECT(expiry_date) ON TABLE tower_sessions.session TO reverie_readonly;

--------------------------------------------------------------------------------
-- 12. Seed data
--------------------------------------------------------------------------------

INSERT INTO public.metadata_sources (id, display_name, kind, enabled, base_priority, config)
VALUES
    ('opf',         'OPF Metadata',   'file', true, 100, '{}'),
    ('manual',      'Manual Override', 'user', true,  10, '{}'),
    ('openlibrary', 'Open Library',   'api',  true, 100, '{}'),
    ('googlebooks', 'Google Books',   'api',  true, 100, '{}'),
    ('hardcover',   'Hardcover',      'api',  true,  90, '{}'),
    ('ai',          'AI-assisted',    'ai',   true, 500, '{}');

INSERT INTO public.settings DEFAULT VALUES;
